apiVersion: v1
kind: Service
metadata:
  name: joomla-service
spec:
  type: LoadBalancer
  selector:
    app: joomla
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
      - env:
        - name: JOOMLA_DB_HOST
          value: mariadb
        - name: JOOMLA_DB_PASSWORD
          value: K31DPI1vBx8vzCvFP9BQIKwsQgPLQi  
        image: joomla
        imagePullPolicy: IfNotPresent
        name: joomla
        ports:
        - containerPort: 80
          protocol: TCP

