apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-unifi
  namespace: unifi
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    #email: $EMAIL_ADDRESS
    email: keith@hubner.co.uk
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-unifi
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-unifi
  namespace: unifi
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      #storage: $VOLUME_SIZE
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: unifi
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/London
        image: jacobalberty/unifi:stable-6
        imagePullPolicy: IfNotPresent
        name: unifi-controller
        ports:
        - containerPort: 3478
          name: stun
          protocol: UDP
        - containerPort: 8080
          #hostPort: 8080
          name: device-comms
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /unifi
          name: unifi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: unifi
        persistentVolumeClaim:
          claimName: pvc-unifi


#docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Africa/Johannesburg' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:stable
---
apiVersion: v1
kind: Service
metadata:
  namespace: unifi
  creationTimestamp: null
  labels:
    app: unifi
  name: unifi-srv
spec:
  ports:
    - name: "3478"
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    app: unifi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: unifi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-unifi
    ingress.kubernetes.io/ssl-redirect: "true"  
  name: unifi
spec:
  tls:
    - hosts:
      #- bw.$CLUSTER_ID.k8s.civo.com
      - unifi.3e21f49e-9a2b-4cbe-af79-e6b272a9dff7.k8s.civo.com
      secretName: letsencrypt-prod-unifi  
  rules:
  #- host: bw.$CLUSTER_ID.k8s.civo.com
  - host: unifi.3e21f49e-9a2b-4cbe-af79-e6b272a9dff7.k8s.civo.com
    http:
      paths:
      - backend:
          serviceName: unifi-srv
          servicePort: 8080  